#!/bin/bash -e

set -e

# Source variables from config.conf file
. config.conf
 

##############################################################################
############################        INIT          ############################
##############################################################################
 

##############################################################################
############################        MAIN          ############################
##############################################################################

for arch in "${TARGET_ARCHS[@]}"
do
    mkdir -p $OPENH264_BUILD_OUT_PATH/$arch/lib
    mkdir -p $OPENH264_BUILD_OUT_PATH/$arch/include/wels

    # Copiar os arquivos de cabeçalho
    cp -r -v $DOWNLOAD_DIR/$OPENH264_DIR_NAME/api/wels $OPENH264_BUILD_OUT_PATH/$arch/include/wels

    # Fazer o download e extrair os arquivos de acordo com a arquitetura
    if [ "$arch" == "armeabi-v7a" ]
    then
        curl -o openh264-${arch}.bz2 http://ciscobinary.openh264.org/libopenh264-2.3.0-android-arm.6.so.bz2
    elif [ "$arch" == "x86" ]
    then
        curl -o openh264-${arch}.bz2 http://ciscobinary.openh264.org/libopenh264-2.3.0-android-x86.6.so.bz2
    elif [ "$arch" == "x86_64" ]
    then
        curl -o openh264-${arch}.bz2 http://ciscobinary.openh264.org/libopenh264-2.3.0-android-x64.6.so.bz2
    elif [ "$arch" == "arm64-v8a" ]
    then
        curl -o openh264-${arch}.bz2 http://ciscobinary.openh264.org/libopenh264-2.3.0-android-arm64.6.so.bz2    
    fi
    bzcat openh264-${arch}.bz2 > libopenh264.so
    mv ./libopenh264.so $OPENH264_BUILD_OUT_PATH/$arch/lib/libopenh264.so
done

echo "Finished downloading OpenH264! Check output folder: ${OPENH264_BUILD_OUT_PATH}"

set +e
