#!/bin/bash -e

set -e

# Source variables from config.conf file
. config.conf
 
 
 
# settings
NDK_PATH=/opt/hostedtoolcache/ndk/r28/x64  
INSTALL_DIR=$OPENH264_BUILD_OUT_PATH   
OPENH264_SOURCE_DIR=$DOWNLOAD_DIR/$OPENH264_DIR_NAME   
API_LEVEL=28  
TARGET_ARCHS=("armeabi-v7a" "arm64-v8a" "x86" "x86_64")

# Preparação
mkdir -p "${INSTALL_DIR}"
# Função de compilação por arquitetura
build_for_arch() {

    ARCH=$1
    case $ARCH in
        "armeabi-v7a")
            TARGET=arm
            ABI="armeabi-v7a"
            ;;
        "arm64-v8a")
            TARGET=arm64
            ABI="arm64-v8a"
            ;;
        "x86")
            TARGET=x86
            ABI="x86"
            ;;
        "x86_64")
            TARGET=x86_64
            ABI="x86_64"
            ;;
        *)
            echo "Arquitetura desconhecida: $ARCH"
            exit 1
            ;;
    esac

    echo "Compilando para $ARCH..."

    # Diretórios de saída para a arquitetura atual
    BUILD_DIR=$OPENH264_SOURCE_DIR/build/$ARCH
    OUTPUT_DIR=$INSTALL_DIR/$ARCH
    mkdir -p "$BUILD_DIR"
    mkdir -p "$OUTPUT_DIR"

    # Exportar variáveis do NDK
    export NDKROOT=$NDK_PATH
    export TARGET=$TARGET
    export NDKLEVEL=$API_LEVEL

    # Limpar compilações anteriores
    cd "$OPENH264_SOURCE_DIR" || exit
     
    if make clean >/dev/null 2>&1; then
        echo "Successfull cleanup"
    else
        echo "Target 'clean' not found, continuing..."
    fi
    
    echo "Building"
    make OS=android NDKROOT=$NDK_PATH TARGET=$TARGET NDKLEVEL=$API_LEVEL 
    echo "Install"
    make install PREFIX=$BUILD_DIR 

    # Copiar os resultados para o diretório de instalação
    cp -r "$BUILD_DIR/lib" "$OUTPUT_DIR/"
    cp -r "$BUILD_DIR/include" "$OUTPUT_DIR/"
    echo "Arquivos instalados para $ARCH em $OUTPUT_DIR"
}

# Compilar para cada arquitetura
for ARCH in "${TARGET_ARCHS[@]}"; do
    build_for_arch "$ARCH"
done
 
echo "Finished building OpenH264! Check output folder: ${OPENH264_BUILD_OUT_PATH}"

set +e
