name: Scripts

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare Environment
      run: |
        cd ${{ github.workspace }}
        sudo mkdir -p /home/lib
        apt-get update
        apt-get purge -y openjdk*
        apt-get install -y openjdk-8-jdk

        DEPS="unzip git curl bzip2 binutils make autoconf openssl \
          libssl-dev libopus0 libpcre3 libpcre3-dev build-essential nasm python2 swig" 
        sh -c "dpkg --add-architecture i386; apt-get update && apt-get -y upgrade && apt-get install -y ${DEPS}"
    - name: Prepare build system
      run: |
        cd ${{ github.workspace }}
        sudo ./prepare-build-system
    - name: Build openssl
      run: |
        cd ${{ github.workspace }}
        sudo ./openssl-build-target-archs
    - name: Build openh264
      run: |
        cd ${{ github.workspace }}
        sudo ./openh264-build-target-archs
    - name: Build opus
      run: |
        cd ${{ github.workspace }}
        sudo ./opus-build
    - name: Build pjsua2
      run: |
        cd ${{ github.workspace }}
        sudo ./build
    - name: Finalize
      run : |
        echo "done building"
    - uses: actions/upload-artifact@v3
      with:
        name: lipjsua2-android
        path: /home/lib