name: Scripts

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build libpjsua2 and external libs (libopenh264, libssl, libcrypto, libopus)
      run: |
        sudo su 
        cd ${{ github.workspace }}
        sudo ./prepare-build-system
        sudo ./openssl-build-target-archs
        sudo ./openh264-build-target-archs
        sudo ./opus-build
        sudo ./build