name: Release

on:
  push:
    tags: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3 
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        check-latest: true
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Prepare Environment
      run: |
        cd ${{ github.workspace }}
        sudo mkdir -p /home/runner/libpjsua2/lib S

        DEPS="unzip git curl bzip2 binutils make autoconf openssl \
          libssl-dev libopus0 libpcre3 libpcre3-dev build-essential nasm python2 swig" 
        sudo sh -c "dpkg --add-architecture i386; apt-get update && apt-get -y upgrade && apt-get install -y ${DEPS}"
    - name: Prepare build system
      run: |
        cd ${{ github.workspace }}
        sudo ./prepare-build-system
    - name: Build openssl
      run: |
        cd ${{ github.workspace }}
        sudo ./openssl-build-target-archs
    - name: Build bcg729
      run: |
        cd ${{ github.workspace }}
        sudo ./bcg729-build
    - name: Build openh264
      run: |
        cd ${{ github.workspace }}
        sudo ./openh264-build-target-archs
    - name: Build opus
      run: |
        cd ${{ github.workspace }}
        sudo ./opus-build
    - name: Build pjsua2
      run: |
        cd ${{ github.workspace }}
        sudo ./build
        sudo tar -zcvf libpjsua2.tar.gz /home/runner/libpjsua2
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./libpjsua2.tar.gz
        asset_name: libpjsua2.tar.gz
        asset_content_type: application/gzip
    