name: Release

on:
  push:
    tags: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: Prepare Environment
      run: |
        cd ${{ github.workspace }}
        sudo mkdir -p /home/lib
        sudo apt-get update
        sudo apt-get purge -y openjdk*
        sudo apt-get install -y openjdk-8-jdk

        DEPS="unzip git curl bzip2 binutils make autoconf openssl \
          libssl-dev libopus0 libpcre3 libpcre3-dev build-essential nasm python2 swig" 
        sudo sh -c "dpkg --add-architecture i386; apt-get update && apt-get -y upgrade && apt-get install -y ${DEPS}"
    - name: Prepare build system
      run: |
        cd ${{ github.workspace }}
        sudo ./prepare-build-system
    - name: Build openssl
      run: |
        cd ${{ github.workspace }}
        sudo ./openssl-build-target-archs
    - name: Build openh264
      run: |
        cd ${{ github.workspace }}
        sudo ./openh264-build-target-archs
    - name: Build opus
      run: |
        cd ${{ github.workspace }}
        sudo ./opus-build
    - name: Build pjsua2
      run: |
        cd ${{ github.workspace }}
        sudo ./build
    - name: Create release
      run: |
        sudo tar -czvf /home/lib
    - name: upload android artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_path: ./lib.tar.gz
        asset_name: lib.tar.gz
        asset_content_type: application/gzip
    